language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: required

env:
  - NETCOMMONS_VERSION=master DB=mysql
global:
  - secure: "CStEE1J8/QO1txqDomDNv0l4JhvVOkoEOXUgy14WQYUGgAsxYvBCskBB10Kn+l93882dKN6i98YbHYvrXcBzDxoe07PZReh1/b4zbPs5II6fQ0BD7MBMpvaxQxmaetdBCXNzXUps5q9y0OUYUlAHSNdek90H6jDYs3n1CoCzmjg="
  - GIT_COMMITTER_NAME=akagane99
  - GIT_COMMITTER_EMAIL=akagane99@gmail.com
  - GIT_AUTHOR_NAME=akagane99
  - GIT_AUTHOR_EMAIL=akagane99@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - . tools/build/plugins/cakephp/travis/pre.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
